name: Jest tests
on: [pull_request]

jobs:
    custom_test:
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'Do not run tests') == false 
        name: Test locally using act
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test coverage
              uses: ArtiomTr/jest-coverage-report-action@v1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  test_script: npx react-scripts test src  --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"

            - name: Create coverage report
              run: npm test -- --coverage --watchAll=false --coverageDirectory=jest-coverage
              continue-on-error: true
            - uses: actions/upload-artifact@v2
              with:
                name: Coverage-report
                path: jest-coverage/lcov-report/