# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
  push:
    branches:
      - master
      - workflows

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - uses: azure/docker-login@v1
    #   with:
    #     login-server: ${{ secrets.ACR_URL }}
    #     username: ${{ secrets.ACR_USERNAME }}
    #     password: ${{ secrets.ACR_PASSWORD }}
    # - name: docker build
    #   run: |
    #     docker build . -t ${{ secrets.ACR_URL }}/sepes-web:latest
    #     docker push ${{ secrets.ACR_URL }}/sepes-web:latest

    - run: echo ${{ github.ref }}

 # Job running if trigger was from Master branch
  master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: docker build
        run: |
          docker pull ${{ secrets.ACR_URL }}/sepes-web:latest
          docker tag ${{ secrets.ACR_URL }}/sepes-web:latest ${{ secrets.ACR_URL }}/sepes-web:stable
          docker push ${{ secrets.ACR_URL }}/sepes-web:stable

  PR:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: docker build
        run: |
          prNumber="$(cut -d'/' -f3 <<<${{ github.ref }})"
          docker pull ${{ secrets.ACR_URL }}/sepes-web:latest
          docker tag ${{ secrets.ACR_URL }}/sepes-web:latest ${{ secrets.ACR_URL }}/sepes-web:$prNumber
          docker push ${{ secrets.ACR_URL }}/sepes-web:$prNumber